sudo: required
services:
  - docker

before_install:
    - docker build -t hizak/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true hizak/docker-react npm run test -- --watchAll=false
